# Generated by Django 2.0 on 2018-03-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_card_reader_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BusinessCard',
        ),
    ]
